### ISSUE TITLE
Failing tests and 'ggpmisc'

### ISSUE THREAD

**Issue by aphalo** [khodosevichlab/CRMetrics#46]
I am the author of 'ggpmisc'. I submitted a new version and reverse dependency checks are failing becuase of test failure for 'CRMetrics'. Locally I get the same error with both the current CRAN version of 'ggpmisc' and the newly submitted one. However, CRAN reverse checks gets the error only with the new version. As system dependencies are complex, it is quite possible that the errors are unrelated to 'ggpmisc'. I add here the link to the [log file from reverse dependecies check for my CRAN submission](https://win-builder.r-project.org/incoming_pretest/ggpmisc_0.5.3_20230624_110123/) (Available for 7 days). Could you please have a look, and if possible run the tests on a machine that is known to be configured correctly for 'CRMetrics'.

Thanks!

**Comment by aphalo** [comment]
The error is the same that shows up at https://cran.r-project.org/web/checks/check_results_CRMetrics.html

**Comment by rrydbirk** [comment]
Hi @aphalo 

The test issue is caused by https://github.com/kharchenkolab/leidenAlg/issues/13. I'm awaiting this issue to be resolved before I can do anything :-)

Thanks for letting us know about this possibly problem!

/Rasmus
