### ISSUE TITLE
detectDoublets and addDoublets not actually calculating the doublets

### ISSUE THREAD

**Issue by ainsku** [khodosevichlab/CRMetrics#51]
When trying to run `crm$addDoublets()` I get the following error:
`Warning: No results found for method(s): doubletdetectionError in crm$addDoublets(method = "doubletdetection", data.path = "../data/") : 
  No method left to load data for.`

After doing some detective work I'm pretty sure I found part of the problem.

1. When running detectDoublets, it creates a .mtx file for each sample and it saves them in sample_xx.mtx. When trying to run the addDoublets, that function is looking for files named sample_xx.mtx.method, so for example in my case sample_xx.mtx.doubletdetection, so we get the error above.
2. If you rename the files so that addDoublets can find them, the function used to write the .mtx files `Matrix::writeMM` is not compatible with the function in addDoublets to read the files 
(`tmp <- files.list[[met]] %>% 
          lapply(read.delim, sep = ",", header = TRUE) %>% 
          bind_rows() %>% 
          `names<-`(c("scores","labels")) `)
as the separator in the .mtx file is a space and thus creates just one column which raises the following error:
`Error in files.list[[met]] %>% lapply(read.delim, sep = ",", header = TRUE) %>%  : 
  'names' attribute [2] must be the same length as the vector [1]`
and if you fix it by reading the .mtx file with
´´´
tmp <- files.list[[met]] %>% 
          lapply(read.table, sep = "", header = FALSE, skip = 1, na.strings = "", stringsAsFactors = FALSE) %>% 
          bind_rows() %>% 
          `names<-`(c("scores","labels"))
´´´

It finally raises an error
`Error in (function (cond)  : 
  error in evaluating the argument 'x' in selecting a method for function 'rownames<-': Can't transform a data frame with `NA` or `""` names.` which I think might have something to do with the data structure as there are three columns in the data frame, but I didn't wanna look further.

**Comment by rrydbirk** [comment]
Hi @ainsku 

First, please use explicit paths instead of relative, i.e. in your case `"../data/"` should be `/work/your_project/data`. Relative paths can lead to confusing errors.

Second, if you use `detectDoublets()` with `export = TRUE` you should have your matrices saved as `sample_xx.mtx`. Also, you should have a Python script saved as `METHOD.py` - which you need to run first :-) This should create the correctly named files. I'm not sure you've done this before running `addDoublets()`?

/Rasmus

**Comment by ainsku** [comment]
Hi @rrydbirk 

The path is in my Rproject, so that I can just copy paste the code the next time I run this analysis.

I can see my problem now. I did run `detectDoublets()` with `export = TRUE` but I assumed either `detectDoublets()` or `addDoublets()` called on the python script, as I couldn't find in any instructions, that I need to call it separately :-)

-Aino

**Comment by rrydbirk** [comment]
Great, closing this issue then :-)
